### ISSUE TITLE
Error while running server.js

### ISSUE THREAD

**Issue by ubatra13** [appium-boneyard/robots#1]
My tapster is uploaded with standard firmata ... and is connected over USB. When I run following command "node server.js" 

Robot moves straight and hit the bottom and then programs through this error and quit listening. 

Your timely response is much appreciated. 

---

1381100728990 Board Connecting... 
1381100728998 Serial Found possible serial port /dev/cu.usbmodemfd121
1381100729000 Board -> Serialport connected /dev/cu.usbmodemfd121
1381100732295 Board <- Serialport ready /dev/cu.usbmodemfd121
1381100732295 Repl Initialized 

> > Robot listening on port 4242

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1127:5)
    at Function.app.listen (/Users/ub/arduino/workspace/robots-master/node_modules/express/lib/application.js:532:24)
    at Board.<anonymous> (/Users/ub/arduino/workspace/robots-master/bots/tapster/server.js:228:7)
    at Board.EventEmitter.emit (events.js:95:17)
    at Board.<anonymous> (/Users/ub/arduino/workspace/robots-master/node_modules/johnny-five/lib/board.js:309:14)
    at Board.<anonymous> (/Users/ub/arduino/workspace/robots-master/node_modules/johnny-five/lib/board.js:124:18)
    at null.<anonymous> (/Users/ub/arduino/workspace/robots-master/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:399:25) 

---

**Comment by ubatra13** [comment]
okay, please ignore, I just realized the port was indeed in use. Changed the port and it worked. 

node server.js -p 4244
