### ISSUE TITLE
ERROR: translationMatrix is not defined

### ISSUE THREAD

**Issue by ubatra13** [appium-boneyard/robots#2]
Hi 

I followed the instructions and was able to produce calibrate.json, and now I am facing an issue when I am running app and trying to tap. 

ub@ubmacbookpro.local:/Users/ub/arduino/workspace/robots-master/bots/tapster>node server.js -p 4244 -c /path/to/calibration.json
1381109789348 Board Connecting... 
1381109789354 Serial Found possible serial port /dev/cu.usbmodemfd121
1381109789355 Board -> Serialport connected /dev/cu.usbmodemfd121
1381109792650 Board <- Serialport ready /dev/cu.usbmodemfd121
1381109792651 Repl Initialized 

> > Robot listening on port 4244
> > GET /tap/x/150.5/y/140.5: 
> > ReferenceError: translationMatrix is not defined
> >     at convertCoordinatesToPosition (/Users/ub/arduino/workspace/robots-master/bots/tapster/server.js:139:13)
> >     at /Users/ub/arduino/workspace/robots-master/bots/tapster/server.js:212:15
> >     at callbacks (/Users/ub/arduino/workspace/robots-master/node_modules/express/lib/router/index.js:161:37)
> >     at param (/Users/ub/arduino/workspace/robots-master/node_modules/express/lib/router/index.js:135:11)
> >     at param (/Users/ub/arduino/workspace/robots-master/node_modules/express/lib/router/index.js:132:11)
> >     at param (/Users/ub/arduino/workspace/robots-master/node_modules/express/lib/router/index.js:132:11)
> >     at pass (/Users/ub/arduino/workspace/robots-master/node_modules/express/lib/router/index.js:142:5)
> >     at Router._dispatch (/Users/ub/arduino/workspace/robots-master/node_modules/express/lib/router/index.js:170:5)
> >     at Object.router (/Users/ub/arduino/workspace/robots-master/node_modules/express/lib/router/index.js:33:10)
> >     at next (/Users/ub/arduino/workspace/robots-master/node_modules/express/node_modules/connect/lib/proto.js:199:15)

**Comment by formiganinja** [comment]
Are you running server.js using the calibration file ? 

node server.js -c my_calibration.json
